version: '3'

services:
  app:
    build: .
    container_name: strider-challenge-app
    command: .docker/start.sh
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    networks:
      - strider

  db:
    image: postgres:14.4
    container_name: strider-challenge-database
    volumes:
      - challenge-strider-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=posterr
      - TZ="America/Maceio"
    ports:
      - "5432:5432"
    networks:
      - strider


networks:
  strider:
    driver: 'bridge'

volumes:
  challenge-strider-db: { }