version: '3'

services:
  app:
    build: .
    container_name: strider-challenge-app
    command: .docker/start-prod.sh
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    networks:
      - strider

